services:
  nbs-dataaccess-mssql:
    build: ./db
    container_name: nbs-dataaccess-mssql
    ports:
      - 1433:1433
    volumes:
      - nbs-mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - SQLCMDPASSWORD=fake.fake.fake.1234
      - SA_PASSWORD=fake.fake.fake.1234
    networks:
      - etldatapipeline

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - etldatapipeline

  broker:
    image: confluentinc/cp-kafka:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: 'INTERNAL://broker:29092,EXTERNAL://broker:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    networks:
      - etldatapipeline

  etl-data-pipeline:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - broker
    container_name: etl-data-pipeline
    env_file:
      - etldatapipeline.env
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: broker:29092
    networks:
      - etldatapipeline

volumes:
  nbs-mssql-data:

networks:
  etldatapipeline:
    name: etldatapipeline
    driver: bridge