-- dbo.v_inv_form_code_data source

-- dbo.v_inv_form_code_data source

-- dbo.v_inv_form_code_data source

-- dbo.v_inv_form_code_data source

CREATE OR ALTER VIEW dbo.v_inv_form_code_data AS

SELECT DISTINCT DATA_LOCATION
              ,CODESET.CODE_SET_GROUP_ID
              ,CODESET.CODE_SET_NM
              ,NBS_UI_METADATA.INVESTIGATION_FORM_CD,NBS_UI_METADATA.Last_chg_time
              ,CODE_VALUE_GENERAL.CODE
              ,CODE_VALUE_GENERAL.CODE_SHORT_DESC_TXT
-- INTO #TEMP_INV_FORM_CODE_DATA
FROM NBS_ODSE.DBO.NBS_UI_METADATA WITH (NOLOCK)
        INNER JOIN NBS_SRTE.DBO.CODESET WITH (NOLOCK) ON NBS_UI_METADATA.CODE_SET_GROUP_ID = CODESET.CODE_SET_GROUP_ID
        INNER JOIN NBS_SRTE.DBO.CONDITION_CODE WITH (NOLOCK) ON CONDITION_CODE.INVESTIGATION_FORM_CD = NBS_UI_METADATA.INVESTIGATION_FORM_CD
        INNER JOIN NBS_SRTE.DBO.CODE_VALUE_GENERAL WITH (NOLOCK) ON CODE_VALUE_GENERAL.CODE_SET_NM = CODESET.CODE_SET_NM
        WHERE  question_identifier in (
        'DEM218', 'DEM114', 'INV163',  'INV161',  'DEM126',  'DEM113', 'DEM127', 'INV159', 'INV152', 'DEM155', 'NOT112', 'INV109',  'INV107', 'DEM140',  'DEM116_B', 'DEM139', 'INV145', 'INV150', 'INV151', 'NPP063', 'INV144', 'DEM142', 'INV108',  'DEM152', 'DEM238', 'INV187', 'INV112', 'INV174', 'INV107', 'INV2002')
        AND CODESET.CODE_SET_GROUP_ID IS NOT NULL
-- ORDER BY NBS_UI_METADATA.DATA_LOCATION;