#server:
#  port: '8090'

spring:
  kafka:
    stream:
      input:
        investigation:
          topic-name: cdc.nbs_odse.dbo.Investigation
        defaultData:
          topic-name: cdc.nbs_odse.dbo.Default.input
      output:
        investigation:
          topic-name: cdc.nbs_odse.dbo.Investigation.output
          topic-name-transformed: cdc.nbs_odse.dbo.Investigation.output-transformed
          topic-name-confirmation: cdc.nbs_odse.dbo.Investigation.Confirmation
          topic-name-notification: cdc.nbs_odse.dbo.Investigation.Notification
          topic-name-observation: cdc.nbs_odse.dbo.Investigation.Observation
    streams:
      application-id: debezium-cdc-consumer-app-1
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
  application:
    name: data-reporting-service

logging:
  # Only one config can be active at a time
  config: classpath:logback-config.xml
  file:
    name: CommonUtil.log
    path: logs