spring:
  kafka:
    topic:
      investigation: nrt_investigation
      observation: nrt_observation
      organization: nrt_organization
      patient: nrt_patient
    group-id: nbs_nrt_post_processing
    consumer:
      maxPollIntervalMs: 30000
      maxConcurrency: 5
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    admin:
      auto-create: true
  application:
    name: data-reporting-service
    batch-size: 5
  datasource:
    password: ${DB_PASSWORD:-fake.fake.fake.1234}
    username: ${DB_USERNAME:-sa}
    url: jdbc:sqlserver://${DB_URL:localhost}:1433;databaseName=${DB_RDB:NBS_RDB};encrypt=true;trustServerCertificate=true;
  jpa:
    properties:
      javax.persistence.query.timeout: -1
#  liquibase:
#    change-log: db/changelog/db.changelog-master.yaml
#logging:
#  # Only one config can be active at a time
#  config: classpath:logback-config.xml
#  file:
#    name: PostProcessingService.log
#    path: ${DA_LOG_PATH:logs}
server:
  port: '8090'