spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
    stream:
      input:
        provider:
          topic-name: cdc.nbs_odse.dbo.Provider
          output-topic-name: cdc.nbs_odse.dbo.Provider.output
        ct-contact:
          topic-name: cdc.nbs_odse.dbo.CT_contact
        participation:
          topic-name: cdc.nbs_odse.dbo.Participation
        person:
          topic-name: cdc.nbs_odse.dbo.Person
        nbs-pages:
          topic-name: cdc.nbs_odse.dbo.NBS_page
    streams:
      application-id: debezium-cdc-consumer-app-1
    bootstrap-servers: localhost:9092
  application:
    name: etl-data-pipeline
  datasource:
    password: ${DB_PASSWORD:fake.fake.fake.1234}
    username: ${DB_USERNAME:sa}
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;}
logging:
  #  Only one config can be active at a time
  config: classpath:logback-config.xml
LOG_PATH: ${DI_LOG_PATH:/tmp/etl-data-pipeline/}
server:
  port: '8090'
