spring:
  kafka:
    stream:
      input:
        ldfdata:
          topic-name: nbs_state_defined_field_data
      output:
        ldfdata:
          topic-name-reporting: nrt_ldf_data
          topic-name-es: elastic_search_ldf_data

    streams:
      application-id: ${KAFKA_CONSUMER_APP:ldfdata-reporting-consumer-app}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    admin:
      auto-create: true
  application:
    name: ldfdata-reporting-service
  datasource:
    password: ${DB_PASSWORD:-fake.fake.fake.1234}
    username: ${DB_USERNAME:-sa}
    url: jdbc:sqlserver://${DB_URL:localhost}:1433;databaseName=${DB_ODSE:NBS_ODSE};encrypt=true;trustServerCertificate=true;
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
logging:
  # Only one config can be active at a time
  config: classpath:logback-config.xml
  file:
    name: LdfDataService.log
    path: ${DA_LOG_PATH:logs}
server:
  port: '8097'