spring:
  kafka:
    stream:
      input:
        observation:
          topic-name: nbs_Observation
      output:
          observation:
            topic-name-reporting: nrt_observation
            topic-name-es: elastic_search_observation
    streams:
      application-id: ${KAFKA_CONSUMER_APP:observation-reporting-consumer-app}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    admin:
      auto-create: true
  application:
    name: investigation-reporting-service
  datasource:
    password: ${DB_PASSWORD:-fake.fake.fake.1234}
    username: ${DB_USERNAME:-sa}
    url: jdbc:sqlserver://${DB_URL:localhost}:1433;databaseName=${DB_ODSE:NBS_ODSE};encrypt=true;trustServerCertificate=true;
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
logging:
  # Only one config can be active at a time
  config: classpath:logback-config.xml
  file:
    name: ObservationService.log
    path: ${DA_LOG_PATH:logs}
server:
  port: '8091'
