spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
    stream:
      input:
        person:
          topic-name: cdc.NBS_ODSE.dbo.Person
        provider:
          topic-name: cdc.NBS_ODSE.dbo.Provider.input
        patient:
          topic-name: cdc.NBS_ODSE.dbo.Patient.input
        organization:
          topic-name: cdc.NBS_ODSE.dbo.Organization.input
        observation:
          topic-name: cdc.NBS_ODSE.dbo.Observation.input
        defaultData:
          topic-name: cdc.NBS_ODSE.dbo.Default.input
      output:
          provider:
            topic-name: cdc.nbs_odse.dbo.Provider.output
          patient:
            topic-name: cdc.nbs_odse.dbo.Patient.output
          organization:
            topic-name: cdc.nbs_odse.dbo.Organization.output
          observation:
            topic-name: cdc.nbs_odse.dbo.Observation.output

    streams:
      application-id: debezium-cdc-consumer-app-1
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    admin:
      auto-create: true
  application:
    name: data-reporting-service
  datasource:
    password: ${DB_PASSWORD:-fake.fake.fake.1234}
    username: ${DB_USERNAME:-sa}
    url: jdbc:sqlserver://${DB_URL:localhost}:1433;databaseName=${DB_ODSE:NBS_ODSE};encrypt=true;trustServerCertificate=true;
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
logging:
  #  Only one config can be active at a time
#  config: classpath:logback-config.xml
  file:
    name: ObservationService.log
    path: ${DA_LOG_PATH:logs}
server:
  port: '8090'
