name: Build and push data-reporting-service image to ECR
on:
  push:
    branches:
      - main
      - master
      - rel-**
    paths-ignore:
      - "docker-compose.yml"
      - "**.md"
jobs:
  call-build-person-reporting-microservice-container-workflow:
    name: Build Person Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: person-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/person-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
  call-build-organization-reporting-microservice-container-workflow:
    name: Build Organization Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: organization-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/organization-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
