name: Build and push data-reporting-service image to ECR
on:
  push:
    branches:
      - main
      - master
      - rel-**
      - CNDIT-* # ToDo: Delete this before merge to main
    paths-ignore:
      - "docker-compose.yml"
      - "**.md"
jobs:
 
  # person-reporting-microservice
  call-build-person-reporting-microservice-container-workflow:
    name: Build Person Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: person-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/person-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
 
  # organization-reporting-microservice
  call-build-organization-reporting-microservice-container-workflow:
    name: Build Organization Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: organization-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/organization-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
  
  # investigation-reporting-microservice
  call-build-investigation-reporting-microservice-container-workflow:
    name: Build Investigation Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: investigation-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/investigation-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
    
  # post-processing-reporting-microservice
  call-build-post-processing-reporting-microservice-container-workflow:
    name: Build post-processing Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: post-processing-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/post-processing-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  # observation-reporting-microservice
  call-build-observation-reporting-microservice-container-workflow:
    name: Build Observation Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: observation-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/observation-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

 # LdfData-reporting-microservice
  call-build-ldfdata-reporting-microservice-container-workflow:
    name: Build LdfData Reporting Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: ldfdata-reporting-service
      dockerfile_relative_path: -f ./data-reporting-service/ldfdata-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

